import type { Metadata } from "next";
import "../app/styles/global.css";

export const metadata: Metadata = {
  title: "MARAI.P",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
